import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

test('private web app exposes personal cockpit regions', async () => {
  const html = await readFile(new URL('../src/web/public/app.html', import.meta.url), 'utf8');

  assert.match(html, /AuthorOS Personal Cockpit/);
  assert.match(html, /data-testid="session-status"/);
  assert.match(html, /data-testid="next-action"/);
  assert.match(html, /data-testid="task-center"/);
  assert.match(html, /data-testid="quality-loop"/);
  assert.match(html, /data-testid="style-profile"/);
  assert.match(html, /data-testid="next-chapter-card"/);
  assert.match(html, /data-testid="pending-preview"/);
  assert.match(html, /data-testid="chapter-reader"/);
  assert.match(html, /data-testid="assistant-chat"/);
  assert.match(html, /styleRewritePreview/);
  assert.match(html, /文风改写预览/);
  assert.match(html, /应用文风修改/);
  assert.match(html, /当前章节/);
  assert.match(html, /质量环路/);
  assert.match(html, /loadCockpit/);
  assert.match(html, /renderQuality/);
  assert.match(html, /renderStyle/);
  assert.match(html, /renderQuality\(data\.quality, data\.jobs \|\| \[\]\)/);
  assert.match(html, /文风档案/);
  assert.match(html, /尚未绑定文风/);
  assert.match(html, /已绑定/);
  assert.match(html, /生成接入/);
  assert.match(html, /同步到写作生成/);
  assert.match(html, /绑定到当前书/);
  assert.match(html, /renderStyleGeneration/);
  assert.match(html, /api\('\/api\/style\/bind'/);
  assert.match(html, /提炼文风/);
  assert.match(html, /styleProfileName/);
  assert.match(html, /styleReferenceText/);
  assert.match(html, /提炼并绑定/);
  assert.match(html, /仅提炼/);
  assert.match(html, /api\('\/api\/style\/extract'/);
  assert.match(html, /规则预览/);
  assert.match(html, /formatStyleSummary/);
  assert.match(html, /styleHint/);
  assert.match(html, /下一章将使用文风/);
  assert.match(html, /deriveBooklessRecovery/);
  assert.match(html, /确认已有正文后，再读取最新章。/);
  assert.match(html, /jobActionLabel/);
  assert.match(html, /jobPhaseLabel/);
  assert.match(html, /jobStatusLabel/);
  assert.match(html, /读取章节/);
  assert.match(html, /接收任务/);
  assert.match(html, /进行中/);
  assert.match(html, /renderStagePill/);
  assert.match(html, /stageStatusLabel/);
  assert.match(html, /已完成/);
  assert.match(html, /下一步/);
  assert.match(html, /缺失/);
  assert.match(html, /可选/);
  assert.match(html, /watchJob/);
  assert.match(html, /loadLatestChapter/);
  assert.match(html, /api\('\/api\/cockpit'\)/);
  assert.match(html, /api\('\/api\/jobs'\)/);
  assert.match(html, /EventSource/);
  assert.match(html, /completed/);
});
