import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

test('private web app exposes personal cockpit regions', async () => {
  const html = await readFile(new URL('../src/web/public/app.html', import.meta.url), 'utf8');

  assert.match(html, /AuthorOS Personal Cockpit/);
  assert.match(html, /class="desk-shell"/);
  assert.match(html, /data-testid="app-shell"/);
  assert.match(html, /data-testid="session-status"/);
  assert.match(html, /data-testid="resident-shell"/);
  assert.match(html, /data-testid="persistent-session-dock"/);
  assert.match(html, /data-testid="writing-desk"/);
  assert.match(html, /data-testid="desk-sidebar"/);
  assert.match(html, /data-testid="desk-main"/);
  assert.match(html, /data-testid="desk-rail"/);
  assert.match(html, /data-testid="focus-nav"/);
  assert.match(html, /data-testid="mode-switcher"/);
  assert.match(html, /data-mode-target="chapter"/);
  assert.match(html, /data-mode-target="production"/);
  assert.match(html, /data-mode-target="preview"/);
  assert.match(html, /data-mode-target="memory"/);
  assert.match(html, /href="#chapterPanel"/);
  assert.match(html, /href="#qualityWorkbench"/);
  assert.match(html, /href="#previewWorkbench"/);
  assert.match(html, /href="#memoryWorkbench"/);
  assert.match(html, /data-testid="book-context-card"/);
  assert.match(html, /data-testid="main-stage"/);
  assert.match(html, /data-testid="stage-panel-chapter"/);
  assert.match(html, /data-testid="stage-panel-production"/);
  assert.match(html, /data-testid="stage-panel-preview"/);
  assert.match(html, /data-testid="stage-panel-memory"/);
  assert.match(html, /data-testid="model-health-card"/);
  assert.match(html, /data-testid="daily-session-summary"/);
  assert.match(html, /data-testid="cockpit-center"/);
  assert.match(html, /data-testid="assistant-panel"/);
  assert.match(html, /data-testid="assistant-dock"/);
  assert.match(html, /data-testid="assistant-drawer-toggle"/);
  assert.match(html, /data-testid="rail-utilities"/);
  assert.match(html, /data-testid="utility-drawer-model"/);
  assert.match(html, /data-testid="utility-drawer-style"/);
  assert.match(html, /data-testid="utility-drawer-assets"/);
  assert.match(html, /data-testid="utility-drawer-tasks"/);
  assert.match(html, /data-testid="assistant-quick-actions"/);
  assert.match(html, /data-testid="rewrite-intent-panel"/);
  assert.match(html, /data-testid="next-action"/);
  assert.match(html, /data-testid="task-center"/);
  assert.match(html, /data-testid="quality-loop"/);
  assert.match(html, /data-testid="chapter-production-line"/);
  assert.match(html, /data-testid="quality-actions"/);
  assert.match(html, /data-testid="quality-artifacts"/);
  assert.match(html, /data-testid="memory-review"/);
  assert.match(html, /data-testid="memory-review-cards"/);
  assert.match(html, /data-testid="style-profile"/);
  assert.match(html, /data-testid="asset-panel"/);
  assert.match(html, /data-testid="book-commitment-card"/);
  assert.match(html, /data-testid="next-chapter-card"/);
  assert.match(html, /data-testid="pending-preview"/);
  assert.match(html, /data-testid="preview-comparison"/);
  assert.match(html, /data-testid="chapter-reader"/);
  assert.match(html, /data-testid="chapter-list"/);
  assert.match(html, /data-testid="assistant-chat"/);
  assert.match(html, /styleRewritePreview/);
  assert.match(html, /文风改写预览/);
  assert.match(html, /文风预览正文/);
  assert.match(html, /styleRewritePreviewContent/);
  assert.match(html, /stylePreview\.previewContent/);
  assert.match(html, /修改预览正文/);
  assert.match(html, /feedbackPreviewContent/);
  assert.match(html, /quality\.pendingPreview\.previewContent/);
  assert.match(html, /feedbackApplyButton/);
  assert.match(html, /sendMessage\('确认应用修改'\)/);
  assert.match(html, /确认应用修改/);
  assert.match(html, /应用文风修改/);
  assert.match(html, /当前章节/);
  assert.match(html, /质量环路/);
  assert.match(html, /loadCockpit/);
  assert.match(html, /renderQuality/);
  assert.match(html, /function renderModelHealth/);
  assert.match(html, /function renderDailySession/);
  assert.match(html, /function renderProductionLine/);
  assert.match(html, /function renderPreviewComparison/);
  assert.match(html, /function renderMemoryReviewCards/);
  assert.match(html, /renderQualityActions/);
  assert.match(html, /quality\.actions/);
  assert.match(html, /生成内评/);
  assert.match(html, /生成读者模拟/);
  assert.match(html, /生成决策/);
  assert.match(html, /生成记忆更新/);
  assert.match(html, /质量产物/);
  assert.match(html, /查看产物/);
  assert.match(html, /loadQualityArtifact/);
  assert.match(html, /previewCompletedJobArtifact/);
  assert.match(html, /qualityArtifactFromCompletedJob/);
  assert.match(html, /memoryDeltaNameFromCompletedJob/);
  assert.match(html, /qualityArtifactContent/);
  assert.match(html, /api\(`\/api\/quality\/artifacts\/\$\{artifact\.type\}\/\$\{artifact\.chapter\}`\)/);
  assert.match(html, /previewCompletedJobArtifact\(data, watchedJobActions\.get\(id\)\)/);
  assert.match(html, /查看记忆更新/);
  assert.match(html, /预览拆分/);
  assert.match(html, /确认拆分合并/);
  assert.match(html, /结构化更新/);
  assert.match(html, /注释保底/);
  assert.match(html, /归档到记忆/);
  assert.match(html, /loadMemoryDelta/);
  assert.match(html, /previewMemoryDeltaMerge/);
  assert.match(html, /mergeMemoryDelta/);
  assert.match(html, /markMemoryDeltaReviewed/);
  assert.match(html, /memoryDeltaContent/);
  assert.match(html, /api\(`\/api\/memory\/deltas\/\$\{encodeURIComponent\(name\)\}`\)/);
  assert.match(html, /api\(`\/api\/memory\/deltas\/\$\{encodeURIComponent\(name\)\}\/merge-preview`/);
  assert.match(html, /api\(`\/api\/memory\/deltas\/\$\{encodeURIComponent\(name\)\}\/merge`/);
  assert.match(html, /api\(`\/api\/memory\/deltas\/\$\{encodeURIComponent\(name\)\}\/reviewed`/);
  assert.match(html, /renderStyle/);
  assert.match(html, /function renderAssets/);
  assert.match(html, /function loadAssetDetail/);
  assert.match(html, /function renderCommitment/);
  assert.match(html, /renderQuality\(data\.quality, data\.jobs \|\| \[\]\)/);
  assert.match(html, /function setWorkbenchMode/);
  assert.match(html, /function toggleAssistantDock/);
  assert.match(html, /文风档案/);
  assert.match(html, /尚未绑定文风/);
  assert.match(html, /已绑定/);
  assert.match(html, /生成接入/);
  assert.match(html, /同步到写作生成/);
  assert.match(html, /绑定到当前书/);
  assert.match(html, /renderStyleGeneration/);
  assert.match(html, /api\('\/api\/style\/bind'/);
  assert.match(html, /提炼文风/);
  assert.match(html, /styleProfileName/);
  assert.match(html, /styleReferenceText/);
  assert.match(html, /提炼并绑定/);
  assert.match(html, /仅提炼/);
  assert.match(html, /api\('\/api\/style\/extract'/);
  assert.match(html, /规则预览/);
  assert.match(html, /formatStyleSummary/);
  assert.match(html, /styleHint/);
  assert.match(html, /下一章将使用文风/);
  assert.match(html, /deriveBooklessRecovery/);
  assert.match(html, /确认已有正文后，再读取最新章。/);
  assert.match(html, /jobActionLabel/);
  assert.match(html, /jobPhaseLabel/);
  assert.match(html, /jobStatusLabel/);
  assert.match(html, /读取章节/);
  assert.match(html, /接收任务/);
  assert.match(html, /进行中/);
  assert.match(html, /renderStagePill/);
  assert.match(html, /stageStatusLabel/);
  assert.match(html, /已完成/);
  assert.match(html, /下一步/);
  assert.match(html, /缺失/);
  assert.match(html, /可选/);
  assert.match(html, /watchJob/);
  assert.match(html, /loadLatestChapter/);
  assert.match(html, /renderChapterWorkbench/);
  assert.match(html, /loadChapter/);
  assert.match(html, /data-chapter/);
  assert.match(html, /api\('\/api\/cockpit'\)/);
  assert.match(html, /api\(`\/api\/chapters\/\$\{chapterNumber\}`\)/);
  assert.match(html, /api\('\/api\/jobs'\)/);
  assert.match(html, /EventSource/);
  assert.match(html, /completed/);
  assert.match(html, /常驻会话/);
  assert.match(html, /residentService/);
  assert.match(html, /residentBook/);
  assert.match(html, /residentTask/);
  assert.match(html, /resumeSession/);
  assert.match(html, /renderResidentShell/);
  assert.match(html, /announceJobCompletion/);
  assert.match(html, /任务完成/);
  assert.match(html, /下一步建议/);
  assert.match(html, /announceJobFailure/);
  assert.match(html, /failureDetail/);
  assert.match(html, /任务失败/);
  assert.match(html, /renderRecoveryActions/);
  assert.match(html, /recovery\.actions/);
  assert.match(html, /handleRecoveryAction/);
  assert.match(html, /retryMessageForAction/);
  assert.match(html, /showModelConfigAdvice/);
  assert.match(html, /api\('\/api\/model\/doctor'\)/);
  assert.match(html, /data-testid="model-config"/);
  assert.match(html, /模型配置/);
  assert.match(html, /modelApiKey/);
  assert.match(html, /saveModelConfig/);
  assert.match(html, /api\('\/api\/model\/config'/);
  assert.match(html, /formatModelDoctor/);
  assert.match(html, /一键重试/);
  assert.match(html, /检查模型配置/);
  assert.match(html, /回到当前书/);
  assert.match(html, /phaseExplanation/);
  assert.match(html, /renderPhaseNote/);
  assert.match(html, /announceJobProgress/);
  assert.match(html, /announcedProgressEvents/);
  assert.match(html, /watchedJobActions/);
  assert.match(html, /我正在建立这本书的底盘/);
  assert.match(html, /我正在把下一章拆成可写的节拍/);
  assert.match(html, /我正在做一版可确认的修改预览/);
  assert.match(html, /我正在按绑定文风做一版改写预览/);
  assert.match(html, /renderAssistantWelcome/);
  assert.match(html, /quickActionMessage/);
  assert.match(html, /我在这儿，直接说你想推进哪一步。/);
  assert.match(html, /帮我继续推进当前书/);
  assert.match(html, /帮这一章去 AI 味/);
  assert.match(html, /强化章尾钩子/);
  assert.match(html, /保留剧情换文风/);
  assert.match(html, /今日写作台/);
  assert.match(html, /创作导航/);
  assert.match(html, /创作现场/);
  assert.match(html, /文风与资产/);
});
